apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
  - name: BUILD_IMAGE
    description: Reference of the image buildah will produce.
  - name: STORAGE_DRIVER
    description: Set buildah storage driver
    default: vfs
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: BUILD_EXTRA_ARGS
    description: Extra parameters passed for the build command when building images.
    default: ""
  - name: PUSH_EXTRA_ARGS
    description: Extra parameters passed for the push command when pushing images.
    type: string
    default: ""
  - name: REGISTRY_URL
    description: Image registry URL.
    type: string
  - name: OCP_PROJECT
    description: Progetto su cui pushare l'immagine buildata.
    type: string
  workspaces:
  - name: VOLUME
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  steps:

  - name: build
    image: quay.io/buildah/stable:latest
    securityContext:
      privileged: true
    workingDir: $(workspaces.VOLUME.path)
    script: |
      buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
        $(params.BUILD_EXTRA_ARGS) --format=oci \
        --tls-verify=false --no-cache \
        -f $(params.DOCKERFILE) -t $(params.BUILD_IMAGE) .
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers

  - name: push
    image: quay.io/buildah/stable:latest
    workingDir: $(workspaces.VOLUME.path)
    script: |
      cd $(workspaces.VOLUME.path) \
      && ARTIFACT_VERSION=`cat version.txt` \
      && buildah --storage-driver=$(params.STORAGE_DRIVER) push \
        $(params.PUSH_EXTRA_ARGS) --tls-verify=false \
        --digestfile $(workspaces.VOLUME.path)/image-digest $(params.BUILD_IMAGE) \
        $(params.REGISTRY_URL)/$(params.OCP_PROJECT)/$(params.BUILD_IMAGE):${ARTIFACT_VERSION}
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers

  - name: digest-to-results
    image: quay.io/buildah/stable:latest
    script: cat $(workspaces.VOLUME.path)/image-digest 

  volumes:
  - name: varlibcontainers
    emptyDir: {}