kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: clean-volume
spec:
  workspaces:
  - name: VOLUME
  steps:
    - name: clean-volume
      image: alpine
      script: |
        rm -rf $(workspaces.VOLUME.path)/*; rm -rf $(workspaces.VOLUME.path)/.[a-zA-Z_]*; pwd; ls -la $(workspaces.VOLUME.path);