apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repository
spec:
  workspaces:
  - name: VOLUME
  params:
  - name: REPOSITORY_URL
    type: string
    description: Url of the git repository to clone.
  - name: BRANCH_NAME
    type: string
    description: Branch di cui eseguire il clone.
  results:
  - name: ARTIFACT_VERSION
    description: Artifact version (version in pom.xml file + git hash)
  steps:

  - name: git-clone
    image: alpine/git:latest
    script: |
      git clone -b $(params.BRANCH_NAME) "$(params.REPOSITORY_URL)" $(workspaces.VOLUME.path)

  - name: store-artifact-version
    image: alpine/git:latest
    workingDir: $(workspaces.VOLUME.path)
    script: |
      # GET THE VERSION OF THE SOFTWARE FROM pom.xml FILE
      version=$(cat pom.xml  | grep '<version>' | head -1 | egrep  '[1-9|.]+'  | sed 's#<version>##g' | sed 's#</version>##g' | xargs)

      # GET THE HASH FOR THE HEAD COMMIT
      hash=$(git rev-parse HEAD | cut -c1-7)

      # UPDATE THE VERSION OF THE SOFTWARE IN pom.xml WITH THE COMMIT HASH
      sed -i "s#<version>${version}</version>#<version>${version}-${hash}</version>#g" pom.xml

      #echo ${version}-${hash} >> version.txt 
      # SAVE THE VERSION AND THE HASH IN A RESULT VARIABLE
      echo ${version}-${hash}| tee $(results.ARTIFACT_VERSION.path)
