apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app
spec:
  workspaces:
  - name: VOLUME
  params:
  - name: BUILD_IMAGE
    type: string
  - name: OCP_PROJECT
    type: string
    description: Progetto OpenShift su cui deployare l'applicazione.
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      script: |
        cd $(workspaces.VOLUME.path) \
        && ARTIFACT_VERSION=`cat version.txt` \
        && oc project $(params.OCP_PROJECT) \
        && oc tag  $(params.BUILD_IMAGE):${ARTIFACT_VERSION} $(params.BUILD_IMAGE):latest