apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app
spec:
  workspaces:
  - name: VOLUME
  params:
  - name: ARTIFACT_VERSION
    type: string
  - name: BUILD_IMAGE
    type: string
  - name: OCP_PROJECT
    type: string
    description: Progetto OpenShift su cui deployare l'applicazione.
  steps:
  - name: patch
    image: quay.io/openshift/origin-cli:latest 
    workingDir: $(workspaces.VOLUME.path)
    script: |
      oc project $(params.OCP_PROJECT)
      oc tag $(params.BUILD_IMAGE):$(params.ARTIFACT_VERSION) $(params.BUILD_IMAGE):latest
      oc get deployment $(params.BUILD_IMAGE) || (oc new-app $(params.BUILD_IMAGE) && oc expose service/$(params.BUILD_IMAGE))
