apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-demo-tt
spec:
  params:
  - name: truncated_sha
  - name: git_repo_url
  - name: git_repo_name

  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: springapp-deploy-run-$(tt.params.truncated_sha)
    spec:
      serviceAccountName: pipeline
      serviceAccountNames:
        - taskName: build-image
          serviceAccountName: build-bot
      pipelineRef:
        name: pipeline-demo
      params:
        - name: "ARTIFACT_VERSION"
          value: ""
        - name: "REPOSITORY_URL"
          value: "$(tt.params.git_repo_url).git"
        - name: REGISTRY_URL
          value: image-registry.openshift-image-registry.svc:5000
        - name: "BUILD_IMAGE"
          value: "$(tt.params.git_repo_name)"
        - name: "OCP_PROJECT"
          value: "project-target-test"
        - name: "BRANCH_NAME"
          value: "main"
        - name: "COMMIT_ID"
          value: "$(tt.params.truncated_sha)"
      workspaces:
      - name: TKN_VOLUME
        persistentVolumeClaim:
          claimName: pvc-pipeline-demo