apiVersion: v1
kind: Template
metadata:
  name: nexus3
  annotations:
    openshift.io/display-name: "Nexus application"
    description: "Nexus artifact Repository Template"
    tags: "nexus, devops"
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: nexus3-pvc
    labels:
      app: nexus3
  spec:
    storageClassName: ${SC_NAME}
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${PVC_SIZE}
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    volumes:
    - name: nexus3-volume
      persistentVolumeClaim:
        claimName: nexus3-pvc
    replicas: 1
    selector:
      deploymentconfig: nexus3
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: nexus3
      spec:
        containers:
          - name: nexus3
            image: sonatype/nexus3
            env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: -XX:ActiveProcessorCount=4
            ports:
              - containerPort: 8081
                protocol: TCP
            resources: {}
            volumeMounts:
              - name: nexus3-volume
                mountPath: /nexus-data
        volumes:
        - name: nexus3-volume
          persistentVolumeClaim:
            claimName: nexus3-pvc
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: nexus3
    labels:
      app: nexus3
  spec:
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: 8081-tcp
    selector:
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: nexus3
  spec:
    port:
      targetPort: 8081-tcp
    to:
      kind: Service
      name: nexus3
parameters:
- name: SC_NAME
  description: StorageClass to use.
- name: PVC_SIZE
  description: Size of the PersistentVolumeClaim.